from backend.routers.auth import router as auth_router
from backend.routers.users import router as users_router
from backend.routers.roles import router as roles_router
from backend.routers.inventory import router as inventory_router
from backend.routers.procurement import router as procurement_router
from backend.routers.bookings import router as bookings_router
from backend.routers.billing import router as billing_router
from backend.routers.security import router as security_router
from backend.routers.reports import router as reports_router
from backend.routers.audit import router as audit_router
from backend.routers.alerts import router as alerts_router
from backend.routers.settings import router as settings_router
from backend.routers.features import router as features_router
from backend.routers.import_export import router as import_export_router
from backend.routers.backup import router as backup_router
from backend.routers.branding import router as branding_router
from backend.routers.members import router as members_router
from backend.routers.attendance import router as attendance_router
from backend.routers.mess_billing import router as mess_billing_router
from backend.routers.recipes import router as recipes_router
from backend.routers.kitchen import router as kitchen_router
from backend.routers.menu_prices import router as menu_prices_router
from backend.routers.guests import router as guests_router
from backend.routers.attendants import router as attendants_router
from backend.routers.tariffs import router as tariffs_router
from backend.routers.womens_bloc_rates import router as womens_bloc_rates_router
from backend.routers.events import router as events_router
